### ISSUE TITLE
todo list for RequiredFormat_interactive

### ISSUE THREAD

**Issue by ValentineHerr** [VincyaneBadouard/TreeData#10]
- [x] ask what status represents a living tree vs a dead tree (listing all options they have in the status column)
- [x] ask what indicates a commercial species
- [x] plotArea + Units
- [x]  put back asking about plot  and subplot name (see [this comment](https://github.com/VincyaneBadouard/TreeData/commit/8c15a147c4c9475ead1c7ccb74ad24271069c0e9#r65943022))
- [ ] ask if scientific name has more info than just Genus and species ?
- [x] add option to give date column instead or beside year column --> also ask for date format

**Comment by ValentineHerr** [comment]
closing this, I think it is obsolete
