### ISSUE TITLE
ToDo list for GeneralErrorsDetection()

### ISSUE THREAD

**Issue by VincyaneBadouard** [VincyaneBadouard/TreeData#11]
- [x] produce test data
- [x] Check duplicated rows
- [x] Check missing values
- [x] Check IdTree unicity (Plot, Subplot, TreeFieldNumber)
- [x] Check duplicated IdTree/IdStem in a census
- [x] Check invariant coordinates per IdTree
- [ ] #82
- [x] Case where the person made a mistake in the IdTree and therefore created a new one even though it is not a recruit: 1 row with unique IdTree, DBH>>> min DBH-> comment column + message
- [ ] #83
- [ ] #84

**Comment by ValentineHerr** [comment]
I converted remaining items in issues that I'll tag as "wish list" because I am not sure we will get to them
