### ISSUE TITLE
todo list for app

### ISSUE THREAD

**Issue by ValentineHerr** [VincyaneBadouard/TreeData#19]
- [x] implement `ReversedRequiredFormat` (see #28)
- [x] handle decimal year format for date of measurement
- [ ] ask user if want to untidy or not (to get in other Profile/s format)
- [x] keep some original columns (status, scientific name, dbh, circ...?)
- [x] create and download metadata
- [x] update code that can be downloaded (Do we still want to download code? it is getting complicated)
- [x ] add different profiles
- [x] implement correction functions (see #27 )
- [x] Translate codes

**Comment by ValentineHerr** [comment]
@GeoPicka I believe this is fixed (including the possibility to select an output profile without tree codes when your data does have tree codes)

**Comment by GeoPicka** [comment]
> 

@ValentineHerr thank you for fixing. Yes, retested: handling duplicate code values from different columns and selecting an output profile without tree codes when input profile has tree codes now working great.

**Comment by ValentineHerr** [comment]
closing this and will start new issues as necessary
