### ISSUE TITLE
ToDo list for DiameterCorrection()

### ISSUE THREAD

**Issue by VincyaneBadouard** [VincyaneBadouard/TreeData#22]
- [x] _TaperCorrection()_
- [x] _RegressionInterpolation()_
- [x] Punctual/shift detection
- [x] Punctual correction
- [x] _POM_ change detection & correction
- [x] Shift correction
- [x] _PhylogeneticHierarchicalCorrection()_
- [x] Correction method column
- [x] _Comment_ column
- [x] _DetectOnly_ = FALSE case
- [ ] vérifier qu'il ne reste que dans _DBHCor_ des valeurs saines. NA si pas eu de correction sur une erreur ?

Pathological cases :
- [x] several measurements/year case
- [x] missing year case

- **Doc**:
- [ ] _DiameterCorrection()_ (_IndividualDiameterShiftCorrection()_): document the _coef_ argument and explain the use of exponential (ask @cpiponiot )

- **To implement:**
    - [ ] _POM_ → _CodeMeasure_ et _HOM_ → _POM_ (ask for general advice) @ValentineHerr 
    - [ ] _PhylogeneticHierarchicalCorrection()_  (_ComputeColleaguesGrowthMean()_): add the _YearFilter_ argument to take only the diameters of colleagues that were not measured in those years (the case of the bad year)
    - [ ] What to do with the diameter values of dead trees (do we let a dead tree grow?)
    - [ ] Other type of correction: *CorrectionType* = "*purge* ": put *DBHCor = NA* if aberrant but no correction. and fill in *DiameterCorrectionMeth* = "*purge".*
   - [ ] Propose also the other reading direction: consider the last diameter value of a tree as the reference (*TrustMeasSet = “last”*) (not a good idea).
    - [ ] *taper*: as a character string ? in R language (Valentine says it's not advised to put it in R language because it leaves the possibility to hack the package)

**Idea:**
- [x] Proposed growth decrease limit in relative (annual) and not just absolute (*NegativeGrowthThreshold*)

- **Tests:**
    - [ ] *DiameterCorrectionbytree():* *PioneersGrowthThreshold* well taken into account
    - [ ] *DiameterCorrectionbytree():* Comment when *POM* decreases over time
    - [ ] *DiameterCorrection():* *DBHCorForDeadTrees = FALSE* : check that the dead have not been corrected, and that the dataset size has not changed
    - [ ] *RegressionInterpolation(): Local = TRUE* part
    - [ ] *UniqueMeasurement()*
    - [ ] *Select2FramingValues()*
    - [ ] *OtherCrit* argument in *PhylogeneticHierarchicalCorrection()*

**Comment by ValentineHerr** [comment]
I think we can close this. 
We need to add more tests in general and some of the suggestions to implement are either already implemented or not priorities at the moment.
