### ISSUE TITLE
ToDo list for BotanicalCorrection()

### ISSUE THREAD

**Issue by VincyaneBadouard** [VincyaneBadouard/TreeData#26]
https://docs.ropensci.org/taxize/articles/taxize.html#resolve-taxonomic-name
- [x] No special characters (typography) 
- [x] Check invariant botanical informations per IdTree (1 IdTree = 1 family, 1 scientific and 1 vernacular name)  
- [x] No family name in the genus and species columns (detection of the suffix "aceae" in the genus and species columns (it is specific to the family name) -> Comment (+transfer to the Family column?) (sort(unique(data[grep("aceae", data$genus), genus]))))  
- [x] Family & Scientific names match (*BIOMASS::getTaxonomy*)
- [ ]  Scientific & vernacular names match (Bad idea)
- [x]  Update the scientific botanical names with the current phylogenetic classification
- [x] **add the correction source!**

- **To implement :**
    - [ ] Use the TNRS package?
    - [ ] Handle special cases (can't do more for now) :
        - [ ] Special pattern: *-subsp*.
    - [ ] sensitivity of the number of correct/incorrect characters
    - [ ] *download.file()* to download a file in row (World Flora Online) (but it would be nice to automatically download the most recent file) @ValentineHerr 
    
- The good idea : Return a table with the unique value of all taxa not recognized by *taxonstand* or *worldflora*, on which the user can fill in the correct species name in another column and we join it (and run it through the special characters and spelling checker)
    - [ ] and correct only this table again
    
- **Tests:**
    - [ ] no *Subspecies* in data
    - [ ] I deactivated the test for the TPL correction because I couldn't find a way to pass it to Github actions (because I need data online) @ValentineHerr 
    
 - **Doc:**
    - [ ] *WFOdataSubset* description of variables in *WFOdataSubset.R*

**Comment by ValentineHerr** [comment]
@gabrielareto If you want to work on the Botanical Correction, make sure you look at this issue.

**Comment by gabrielareto** [comment]
[taxize](https://github.com/ropensci/taxize) package includes TNRS among several data sources. But if TNRS package works better (faster, or fails less) we can use it -- we do not need multiple sources of data names, just a central one.

The user's taxonomic backbone will be kept as part of their profile, as the equivalence between the user's names and the central names (TNRS names, for example). Right?

**Comment by ValentineHerr** [comment]
@gabrielareto, are you going to work on the [BotanicalCorretion.R](https://github.com/VincyaneBadouard/TreeData/blob/c345ccbf61d7cd676c437fff1b117ce54975857b/R/BotanicalCorrection.R) function like you had offered?

**Comment by gabrielareto** [comment]
I re-wrote the function. The string manipulation needed depends on the behavior of the taxonomic resolution tool (TNRS package in this case). 
 
Comments about the open boxes above:

Vernacular names: not processed

Phylogenetic classification: follows Tropicos = APG 4, it will be updated as long as TNRS package is well-connected to Tropicos. The APG version is not kept, the same way nothing is kept, regarding the version of the set of accepted names. 

Correction sources: TNRS is mentioned in column names (xxx_returned_by_TNRS) in Data. Specific sources are mentioned in the complete log. With the TestData, 195/200 use Tropicos as a source

Special cases of subspecies, etc.: TNRS is quite robust, it behaves well if things are passed in order

Sensitivity to number of correct/incorrect characters: not evaluated

WFO: discarded but it could be an option. The problem is the string manipulation prior to it -- it needs to be tuned to the particular behaviour of the engine or WorldFlora package. It is possible to automatically download it, though.

Table with unique value of all taxa not recognized, on which the user can fill in the correct species name in another column and we join it (and run it through the special characters and spelling checker): not done. There is a complete log with this and other problems (e.g. synonyms, multiple names within same tree); for the moment the user will have to check the log and improve their original data outside the app.

**Comment by ValentineHerr** [comment]
I am working on some visualization of the Botanical corrections.
What do you guys think of this?

![image](https://user-images.githubusercontent.com/19673377/230960924-eec292f7-59db-4ca3-a855-c6ee7719e484.png)

[...]

![image](https://user-images.githubusercontent.com/19673377/230961080-ec48c7da-2e75-43ba-b7a4-23caffbe37b5.png)

**Comment by ValentineHerr** [comment]
I think we can close this now
