### ISSUE TITLE
ToDo list for RecruitmentCorrection()

### ISSUE THREAD

**Issue by VincyaneBadouard** [VincyaneBadouard/TreeData#50]
- [x]  add _Comment_ in _RecruitCorrection_
- [x]  by _stem_
- [x]  if the user has no '_DBHCor_' column take _Diameter_ but advise to do the diametric correction first
- [x]  if only 1 _DBH_ measured (no _cresc_) -> take _PositiveGrowthThreshold_ as growth
- [x] _minDBH_ in column now
- [ ] Redo the recruitment function (too sensitive): detects trees as overrecruit when they are at '_10, something_': for the moment we leave it, but we can round it up
- [ ] If all _DBH_ have the same value, is it useful to add as many rows as missing census, with always the same _DBH_ value? maybe use _PositiveGrowthThreshold_ instead of _cresc_.
- [ ] Growth of recruits: see in the literature the phylogenetic variables linked or just to ontogenic stage (linked to WD Chave 2009)

**Comment by ValentineHerr** [comment]
@VincyaneBadouard, I am working on the `RecruitCorrection` function and I see the definition of `PositiveGrowthThreshold` parameter as: `A tree widening by more than x cm/year is considered abnormal (numeric, 1 value)` but in the code it looks like it is only used to assign the growth of a tree when there is only one DBH value:

```
# Growth criteria
    if(length(cresc) > 0){ # if there are a growth
      Growth <- cresc[1] # 1st growth value
    }else{Growth <- PositiveGrowthThreshold} # if only 1 DBH value (no cresc)
```

Also, I am not following all of the logic. You are saying that there was a missed recruits looking if the tree is "abnomally big for a first time measurement", based on 'Growth':

```
   # Detection
    #### If the 1st DBH is larger than it would have been if at the previous census it was at the minimum DBH
    if (FirstDBH > (MinDBH + (RecruitYear - PrevCens) * Growth)){ 


      DataTree <- GenerateComment(DataTree,
                                  condition = DataTree[, Year]  %in% RecruitYear,
                                  comment = "This DBH is/was the 1st recorded for this tree,
                                  according to its annual growth and the census done for this plot,
                                  it should have been recruited earlier according to your protocol (MinDBH).")
[...]
```
but then later you do a linear regression to fill the DBH of the missed recruits.

Why not using the linear regression to see if the DBH at the previous census was >MinDBH and if yes, add the row (or, if `DetectOnly`, add the comment on the first time the tree was measured to say that it was probably missed in the previous census)?

**Comment by ValentineHerr** [comment]
I haven't looked at the DiameterCorrection function yet but I am wondering if it would be better to add a parameter in that one to to ask if user wants to add missed recruits, and get rif of `RecruitCorrection`... So we can leverage the growth rates calculated on various taxo levels...
 What do you think @VincyaneBadouard and @cpiponiot ?

**Comment by cpiponiot** [comment]
That sounds like a good idea!
