### ISSUE TITLE
General ToDo list

### ISSUE THREAD

**Issue by VincyaneBadouard** [VincyaneBadouard/TreeData#53]
- [ ] Before correction, return the **%** of measures to correct (how many trees to correct, **%** of error and % of type of error)
- [ ] If the _IdStem_ is not unique (it is found from one _IdTree_ to another), create a variable with the combination of the two and make the corrections with this variable (there must be no error in the _IdTree-IdStem_ associations...)
- [ ] *ErrorsSummary()*: create a *summary* of errors (with what is in the *Comment* column)
- [ ] Put *progressbars* for functions that call functions working by ID @ValentineHerr 
- [ ] Fill in the _vignette_ ([vignettes/TreeData.Rmd)](https://github.com/VincyaneBadouard/TreeData/blob/ab655b769bf17b36c40655cf041f75eb9a03d1c9/vignettes/TreeData.Rmd)
- [ ] Improve test coverage
- [x] Improve code to reduce computation time
- [ ] Sensitivity study of correction methods, ability to recover original values
