### ISSUE TITLE
todo list for RequiredFormat

### ISSUE THREAD

**Issue by ValentineHerr** [VincyaneBadouard/TreeData#9]
- [x] rename the column to the standard names
- [x] coearce column classes
- [x] convert minDBH units
- [x] give a copy of columns @VincyaneBadouard will need, with `CorrectedByApp` suffixe
- [ ] check column classes (for now I am coercing but it may cause issues)
- [x] handle decimal year format for date of measurement
- [ ] détecter le séparateur dans la colonne *ScientificName* pour la séparer en *Genus* et *Species* (pour l'instant demande a l'utilisateur)
- [x] wide to long format
- [x] Proposer 2 cases à l'utilisateur : DBH ou Circ selon ce qu'il a. Nous on utilisera le DBH
- [ ] #81
- [x] proposer des "profils" de métadonnées (list) en input , 
  - [x] et permettre d'en créer (output)
- [x] deal with census date if census year is not there
- [x] creer IdTree si ca n'existe pas
- [x] convert PlotArea  to standard units
- [x] convert SubPlotArea  to standard units
- [x] put back filling in plot and subplot names (after asking their name if they don't have a column) see [this comment](https://github.com/VincyaneBadouard/TreeData/commit/8c15a147c4c9475ead1c7ccb74ad24271069c0e9#r65943022) 
- [x] format date when provided  (still need to ask for it)
- [x] generate year if only date is provided (when that functionality is working)
- [x] deal with life status
- [x] deal with commercial status
- [x] deal with coordinate units

Cas pathologiques :
- [ ] pas que GenusSpecies dans ScientificName (sous-espèce, variété, nom auteur, date) -> a mettre dans une autre col
- [ ] fct dispersion de l'information répétée mais non rentrée (genre pom qui change pas mais qui n'est pas écrit à chaque ligne)
- [ ] Cas où Size/POM/TreeHeight est un code est non une mesure (conserver la colonne code et en créer une nouvelle pour sa traduction en mesure numérique)
- [ ] Cas où PlotArea = c(1 valeur numérique par plot). Quelle forme ? une table ? un vecteur nomme ?

**Comment by GeoPicka** [comment]
@ValentineHerr there is a problem with assigning missing idTree:
If the data is multiple census and inconsistent i.e. data includes different number of census for different plots and/or missing census for stems after they died or before they recruit.

This is an issue for ForestPlots data as only multiple stems have an idTree. (So all single stems require an idTree assigning), and dead trees are only recorded in the first census they are recorded as dead, and recruits are 'missing' from ForestPlots data until the census that they recruit into. 
ForestPlots data has idStem for ALL stems. Is it possible to use this to inform the auto assigning of missing idTree, rather than number and sequence of census? Currently the automated idTree link stems in different plots until the full number of census is reached.

Test data:
[ForestPlots_test2_trees_small.csv](https://github.com/VincyaneBadouard/TreeData/files/9454776/ForestPlots_test2_trees_small.csv)
[ForestPlots_test2_plots_small.csv](https://github.com/VincyaneBadouard/TreeData/files/9454777/ForestPlots_test2_plots_small.csv)

Profile and results:
[ForestPlots_test2_plots_small.zip](https://github.com/VincyaneBadouard/TreeData/files/9454782/ForestPlots_test2_plots_small.zip)

**Comment by GeoPicka** [comment]
@ValentineHerr id_Census not accepting SEOSAW format

Census id for SEOSAW data is e.g. MMB_3_2019.The SEOSAW data doesn't have census number, for census id it uses a combination of the plot id and measurement year.

Is it possible to allow this data format for id_census?

**Comment by ValentineHerr** [comment]
> @ValentineHerr id_Census not accepting SEOSAW format
> 
> Census id for SEOSAW data is e.g. MMB_3_2019.The SEOSAW data doesn't have census number, for census id it uses a combination of the plot id and measurement year.
> 
> Is it possible to allow this data format for id_census?

@GeoPicka, Do you mean that you would like to select more than one columns for id_census and have them be concatenated?
Currently, (if I remember well), if id_census is missing, the year is used to create the census ID. Isn't that enough?

**Comment by GeoPicka** [comment]
> > @ValentineHerr id_Census not accepting SEOSAW format
> > Census id for SEOSAW data is e.g. MMB_3_2019.The SEOSAW data doesn't have census number, for census id it uses a combination of the plot id and measurement year.
> > Is it possible to allow this data format for id_census?
> 
> @GeoPicka, Do you mean that you would like to select more than one columns for id_census and have them be concatenated? Currently, (if I remember well), if id_census is missing, the year is used to create the census ID. Isn't that enough?

hello @ValentineHerr - welcome back from your holidays :) 
 No, there is only 1 column that I'd like to select for id_census, but the contents of that column is not accepted by the app in the download (it instead appears blank). The 1 column in SEOSAW data is called census_id and the format of the data is a string of characters e.g. MMB_3_2019.  Is it possible for you to edit the app to allow that format of data as id_census? 
If not, the year might also be fine to use instead- but it didn't pull the year through in the download as default when the incompatible format census_id was selected- ok? 
I checked and the app does pull through census year when id_census not specified which is good. But during testing, when I specifically selected census year for id_census this didn't work (id_census appeared blank in the download).

**Comment by ValentineHerr** [comment]
> @ValentineHerr there is a problem with assigning missing idTree: If the data is multiple census and inconsistent i.e. data includes different number of census for different plots and/or missing census for stems after they died or before they recruit.
> 
> This is an issue for ForestPlots data as only multiple stems have an idTree. (So all single stems require an idTree assigning), and dead trees are only recorded in the first census they are recorded as dead, and recruits are 'missing' from ForestPlots data until the census that they recruit into. ForestPlots data has idStem for ALL stems. Is it possible to use this to inform the auto assigning of missing idTree, rather than number and sequence of census? Currently the automated idTree link stems in different plots until the full number of census is reached.
> 
> Test data: [ForestPlots_test2_trees_small.csv](https://github.com/VincyaneBadouard/TreeData/files/9454776/ForestPlots_test2_trees_small.csv) [ForestPlots_test2_plots_small.csv](https://github.com/VincyaneBadouard/TreeData/files/9454777/ForestPlots_test2_plots_small.csv)
> 
> Profile and results: [ForestPlots_test2_plots_small.zip](https://github.com/VincyaneBadouard/TreeData/files/9454782/ForestPlots_test2_plots_small.zip)

@GeoPicka I think this should be fixed now. I am still add "_auto" to the IdStem to create the IdTree, just to be make sure it is obvious it was generated in the app. Let me know what you think when you get a chance.

**Comment by GeoPicka** [comment]
> > @ValentineHerr there is a problem with assigning missing idTree: If the data is multiple census and inconsistent i.e. data includes different number of census for different plots and/or missing census for stems after they died or before they recruit.
> > This is an issue for ForestPlots data as only multiple stems have an idTree. (So all single stems require an idTree assigning), and dead trees are only recorded in the first census they are recorded as dead, and recruits are 'missing' from ForestPlots data until the census that they recruit into. ForestPlots data has idStem for ALL stems. Is it possible to use this to inform the auto assigning of missing idTree, rather than number and sequence of census? Currently the automated idTree link stems in different plots until the full number of census is reached.
> > Test data: [ForestPlots_test2_trees_small.csv](https://github.com/VincyaneBadouard/TreeData/files/9454776/ForestPlots_test2_trees_small.csv) [ForestPlots_test2_plots_small.csv](https://github.com/VincyaneBadouard/TreeData/files/9454777/ForestPlots_test2_plots_small.csv)
> > Profile and results: [ForestPlots_test2_plots_small.zip](https://github.com/VincyaneBadouard/TreeData/files/9454782/ForestPlots_test2_plots_small.zip)
> 
> @GeoPicka I think this should be fixed now. I am still add "_auto" to the IdStem to create the IdTree, just to be make sure it is obvious it was generated in the app. Let me know what you think when you get a chance.

Thank you @ValentineHerr .  I can see this is working when I download in a saved profile format, however I am now no longer able to download the zip file in the standard app format. This was working fine yesterday so I'm not sure what the problem is. When I select 'Save all' the file name now appears as dbZIP instead of the upload file name plus .zip. When I navigate to the location of the downloaded files/folder there is nothing there. I tried changing the name of the download to .zip but that doesn't work either. In Rstudio my console displays Warning: Error in grep: invalid 'pattern' argument.
(However, if I set the download format to a saved profile from my desktop the 'save all' file name appears correctly as filename.zip and I am able to then open the downloaded files.)

**Comment by ValentineHerr** [comment]
Hi @GeoPicka, can you give it another thy now?

**Comment by GeoPicka** [comment]
> Hi @GeoPicka, can you give it another thy now?

Thank you @ValentineHerr : now fixed, working great

**Comment by GeoPicka** [comment]
> > Hi @GeoPicka, can you give it another thy now?
> 
> Thank you @ValentineHerr : now fixed, working great

Hi @ValentineHerr the data download bug is now back- unable to download data in the app's standard format- When I select 'Save all' the file name now appears as dbZIP instead of the upload file name plus .zip. But the download works correctly if specify an uploaded profile file.

**Comment by ValentineHerr** [comment]
Closing this now, remaining things will get their own issues
